### PR TITLE
Do not show private fields in system card unless passed -all

### PR DESCRIPTION
**Pull request by Qyriad**

### CODE REVIEW

**Comment by xSke** [comment]
Should this extend to other cards? member card, group card, etc

**Comment by Qyriad** [comment]
Probably, yes, but we only implemented it for system cards in this PR. We can do the others too in another PR if you'd like.

**Comment by xSke** [comment]
This is a change that IMO should be properly announced and "telegraphed" so it would be nice to have it happen all at once

**Comment by Qyriad** [comment]
Gotcha, we'll do that in a bit, then 👍

**Comment by spiralw** [comment]
This branch is quite outdated and I want to generalize the idea a bit more: #404

**Pull request closed without merging**
