### PR TITLE
[doc] Clarifying <group>/<name> into <groupname> in command-list.md

### PR DESCRIPTION
**Pull request by FirePowi**
Open for discussion

### CODE REVIEW

**Comment by FirePowi** [comment]
Can have help with checks, please? I don't understand what's wrong?

**Comment by dev-kittens** [comment]
> Can have help with checks, please? I don't understand what's wrong?

GitHub builds are currently broken. You're only updating documentation, so don't worry about it.

**Comment by FirePowi** [comment]
@dev-kittens Thanks!

**Comment by xSke** [comment]
I've been using `<group>` similar to `<member>`/etc to imply that you can both use the name or the ID. I feel like `<groupname>` would muddle that up, but also there might be an even better way to clarify that somehow?

**Comment by FirePowi** [comment]
@xSke I think `<member>` and `<group>` is better, that just that it was `<name>` and `<name>` is ambiguous for 
`pk;member new <name>`/`pk;group new <name>` as in this command, you can't give the ID, but only a name to give to the new member/group

**Comment by spiralw** [comment]
Merged in 28cd50a5bfc4be61b8f15a9545b0b21511f3bef1.

**Pull request closed without merging**
