### PR TITLE
Make proxy tags not cap-sensitive

### PR DESCRIPTION
**Pull request by UsernameNotAvalible**
This change is pretty simple. It makes proxy tags not be caps-sensitive, so that typing `TT:hi` could also proxy as a member with proxy tags `tt:text` or `tT:text`. If 2 members have the same proxy tag with different capitalization and you try to proxy using the proxy tags, the bot will prioritize whatever member has proxy tags with capitalization closest to how you capitalized it in the message to proxy

### CODE REVIEW

**Comment by UsernameNotAvalible** [comment]
Someone suggested this, so i made it. It could cause problems if someone has 2 members with the same proxy tags with different capitalization, though.

**Comment by spiralw** [comment]
This needs to be an *option* - and by default set to false - whether per member or globally for the system.

**Comment by UsernameNotAvalible** [comment]
What should i name the config option?

**Comment by UsernameNotAvalible** [comment]
I don't think it's possible to access the config info from this context, so it might be near-impossible for me to make this be controlled by a config setting

**Comment by spiralw** [comment]
I'm not very familiar with that code but you should be able to pass it through in `ProxyTagParser.TryMatch`?

**Comment by UsernameNotAvalible** [comment]
I don't think it is possible to have this controlled by a config value without having to rewrite a huge amount of code

**Comment by spiralw** [comment]
oh right, you'd have to add it to MessageContext in SQL

**Pull request closed without merging**
