### PR TITLE
Remove hardcoded prefixes in strings

### PR DESCRIPTION
**Pull request by dev-kittens**
- Created `Context.CommandPrefix`
- Changed `HasCommandPrefix` to actually return the prefix it found instead of just the length of it

### CODE REVIEW

**Comment by xSke** [comment]
Seeing a lot of compile warnings in DiscordUtils, can you check?

**Comment by dev-kittens** [comment]
> Seeing a lot of compile warnings in DiscordUtils, can you check?

Fixed, not sure what I was doing there

**Comment by dev-kittens** [comment]
merge conflicts begone

**Comment by dev-kittens** [comment]
ah oops

**Comment by dev-kittens** [comment]
This PR is very stale. I'll reimplement the changes in a separate PR when the `newdiscord` branch is merged to main.

**Pull request closed without merging**
