### PR TITLE
bot: add member count to system card

### PR DESCRIPTION
**Pull request by xBelladonna**
Just what the title says

### CODE REVIEW

**Comment by xSke** [comment]
Don't have time today to do this myself, but could you change it so it puts the count in parens in the embed title?

**Comment by xBelladonna** [comment]
Sure I'll do it once I'm home from work

**Comment by xSke** [comment]
Bonus: have it display the first 10 or so in short form, then refer to the member list if there are more

**Comment by xBelladonna** [comment]
*sweats nervously*
Sure I'll give it a go

**Comment by xBelladonna** [comment]
Oh god I forgot the commit formatting... I'll just... force push that...

**Comment by xBelladonna** [comment]
Ok, it displays member count in embed title or member field if the system is unnamed now.

**Comment by xSke** [comment]
Could you make it display in the member field title no matter what (and then not in the system name)? Seems more consistent that way.

**Comment by xBelladonna** [comment]
It hath been pushed 👀

**Pull request merged**
