### PR TITLE
Confirm before clearing system/member property

### PR DESCRIPTION
**Pull request by xBelladonna**
- Asks for confirmation before clearing a system or member property (i.e. issuing a command without any parameters)
  - This will provide a buffer between issuing the command with the intention to show the property (which is what `pk;member <name>` does) and actually clearing the property

### CODE REVIEW

**Comment by xBelladonna** [comment]
- Massive rebase with upstream changes
- Yes I force-pushed it, didn't want to have commits saying "Rebased upstream changes" :joy:

**Comment by xBelladonna** [comment]
- Your diff was Too Powerful and confused git so it screwed up the rebase. I deleted the branch, re-created this PR and force-pushed it

**Comment by xBelladonna** [comment]
My god resolving the merge conflicts took way more effort than it should have but it's done. Don't mind all those force-pushes 👀

**Comment by xBelladonna** [comment]
Oh god the conflicts

**Comment by xSke** [comment]
Superseded by #234.

**Pull request closed without merging**
