### PR TITLE
Create an endpoint to get a message's information

### PR DESCRIPTION
**Pull request by goose121**
See #78 except this time it should work

### CODE REVIEW

**Comment by Ryonez** [comment]
Does this return message content?

**Comment by xBelladonna** [comment]
It can't because the db doesn't store messages, and there are no calls to discord's API to fetch the contents

**Comment by Ryonez** [comment]
Alright, just checking as I wasn't 100% sure.

**Comment by xBelladonna** [comment]
Hi OP,
Just letting you know there's been changes to `api_main.py` since your last commit and there's merge conflicts that have to be resolved :')

**Comment by goose121** [comment]
Ah ok, I'll see what's up and resolve the conflicts

**Comment by xSke** [comment]
Added in ca73a215.

**Pull request closed without merging**
