### PR TITLE
Anti hax, no-kek

### PR DESCRIPTION
**Pull request by xBelladonna**
Sends system json file to DMs instead of publicly

### CODE REVIEW

**Comment by Ryonez** [comment]
kek huh?

**Comment by xBelladonna** [comment]
Katie changed it and I didn't check smh

**Comment by xSke** [comment]
SHE SAID DONT ASK

**Comment by Ryonez** [comment]
BUT I WANNA!

Though this does give the idea to maybe shift the bot prefix to the config, or/and to make it adjustable.

**Comment by xSke** [comment]
If you wanna make a PR for that, go ahead :p Otherwise I'll get around to it.... someday......

**Comment by xSke** [comment]
I should just make a proper config file instead of controlling everything with environment variables, maybe.

**Comment by xBelladonna** [comment]
Mostly it just makes me wanna kick Katie's butt :V

**Comment by Ryonez** [comment]
Gotcha.

**Pull request merged**
